### ISSUE TITLE
Running Multiple Bots

### ISSUE THREAD

**Issue by iDJHost** [GwynethLlewelyn/restbot#14]
Considering we're setting a single port & password in configuration.xml, will multiple bots run on a single "RESTBot" service running because of the session id's essentially helping to reduce resource usage as opposed to running multiple services?

Theoretically:
In a "retail" environment would it be best to run a single "RESTBot" service for a unique password and port per client?
(Not selling RESTBot, but rather charging for hosting RESTBot on my dedicated server for clients as an example.)

**Comment by GwynethLlewelyn** [comment]
Remember, I'm just 'inheriting' this ancient piece of software and trying to coerce it to compile under contemporary setups, so my answer may be totally wrong :)

Essentially, I would answer all your questions with 'yes', although I cannot comment on the reasoning behind the original programming. RESTbot consumes an incredible amount of resources, that's for sure. If that is related to LibreMetaverse beneath, or the crude attempt at doing a minimalistic web server from scratch (using direct reads and writes from sockets! agh!), I have no idea. Perhaps this was started so long ago (_circa_ 2007) that Microsoft didn't include the contemporary 'embedded web server' modules as it does today. A full rewrite of RESTbot, using those contemporary modules and libraries, _might_ result in much better code, possibly less resource consumptions, and, most likely, less memory leaks (#8) that not even the garbage collector can get rid of.

In my own production environment, I run multiple bots on the same port/password, with a single instance of RESTbot. While I haven't tested it to see what are the limits, it certainly handles 20 simultaneous bots on four regions with ease.

In an environment with multiple end users (each with their own password), you have two choices. The simplest one would indeed be to replicate several instances, side by side, each running on their own port. The main advantage would be to completely isolate users' bots from each other. The major disadvantages would be 'losing' a port (of which there are many — say, 60k+ — but these are _not_ unlimited!) and, of course, multiple concurrent RESTbot instances _might_ just consume more resources per instance (each leaking memory at different rates...).

Personally, I would stick to one instance (or possibly two, on separate servers, for a degree of redundancy, and having a frontend acting as load balancer — example: nginx) and just handle per-user authentication differently, i.e. not rely on a static file with passwords... that's not a realistic solution for a proper backend that needs to handle with several different users. Instead, there must be some way to deal with authentication, at a higher level (with users stored on Active Domains, or locally authenticated via Samba or PAM or even both :) This, however, requires a bit more patchwork to get it working...

As to using RESTbot commercially, in whatever way you think it can be useful to you, feel free to go ahead — originally, Pleiades released it under the GNU Affero General Public License, which most certainly allows tinkering with the code and including it as part of any package designed to be commercially sold, so long as you openly and freely publish whatever changes you have made.

**Comment by iDJHost** [comment]
Well, I'm not familiar with C# so I'm limited in any help I may be able to offer. I do run a "hosting" company though and bot hosting is 1 of the many offerings I make available. With that being said, I do give credit where credit is do, citing the software names and providing available links to the "creators" site and links for resources for those who want to "DIY". I just keep the software running 24/7 for a small fee.

**Comment by GwynethLlewelyn** [comment]
Thanks :-)
